export const usuarioAtualMock = {
  id: 'usr-joao',
  nome: 'João Pedro Silva',
  curso: 'Ciência da Computação',
  periodo: '6º Período',
  matricula: '202310482',
  email: 'joao.silva@uniacademia.edu.br',
  foto: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=150&auto=format&fit=crop&q=80',
  reputacao: 4.9,
  totalCaronasDadas: 18,
  totalCaronasPagas: 24,
  economiaEstimada: 'R$ 380,00',
  co2Evitado: '145 kg',
  veiculo: {
    modelo: 'Chevrolet Onix Plus',
    cor: 'Prata Metálico',
    placa: 'RTE-4H21',
    capacidade: 4,
  },
  chavePix: 'joao.silva@uniacademia.edu.br',
  preferencias: {
    musica: 'Eclética / Pop & MPB',
    arCondicionado: 'Sempre ligado',
    conversa: 'Tranquilo / Boa conversa',
  },
};

export const caronasIniciaisMock = [
  {
    id: 'carona-1',
    motorista: {
      id: 'usr-caio',
      nome: 'Caio Castilho',
      curso: 'Engenharia de Software',
      foto: 'https://images.unsplash.com/photo-1570295999919-56ceb5ecca61?w=150&auto=format&fit=crop&q=80',
      nota: 4.9,
      alunoVerificado: true,
      celular: '(32) 99821-4412',
    },
    origem: 'São Mateus',
    pontoEncontro: 'Praça do São Mateus (em frente à Igreja)',
    destino: 'Campus Estrela Sul',
    pontoDesembarque: 'Portaria Principal - Bloco B',
    horarioSaida: '18:25',
    tolerancia: '5 min',
    turno: 'Noite',
    valorRateio: 'R$ 6,00',
    vagasTotais: 3,
    vagasDisponiveis: 2,
    carro: 'Hyundai HB20 Cinza • GJF-8921',
    comodidades: ['Ar-condicionado', 'Música leve', 'Porta-malas livre'],
    diasSemana: ['Seg', 'Ter', 'Qua', 'Qui', 'Sex'],
    passageiros: [
      {
        id: 'usr-jonathan',
        nome: 'Jonathan Delmonte',
        curso: 'Ciência da Computação',
        foto: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
      },
    ],
  },
  {
    id: 'carona-2',
    motorista: {
      id: 'usr-gabriel',
      nome: 'Gabriel Caputo',
      curso: 'Sistemas de Informação',
      foto: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
      nota: 5.0,
      alunoVerificado: true,
      celular: '(32) 99145-8833',
    },
    origem: 'Cascatinha',
    pontoEncontro: 'Entrada do Independência Shopping',
    destino: 'Campus Academia (Centro)',
    pontoDesembarque: 'Rua Halfeld / Portão Lateral',
    horarioSaida: '07:15',
    tolerancia: '5 min',
    turno: 'Manhã',
    valorRateio: 'R$ 5,50',
    vagasTotais: 4,
    vagasDisponiveis: 1,
    carro: 'Fiat Pulse Branco • RTY-3A19',
    comodidades: ['Ar-condicionado', 'Porta-malas amplo'],
    diasSemana: ['Seg', 'Ter', 'Qua', 'Sex'],
    passageiros: [
      {
        id: 'usr-nicolas',
        nome: 'Nicolas Isaac',
        curso: 'Ciência da Computação',
        foto: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=150&auto=format&fit=crop&q=80',
      },
      {
        id: 'usr-joao',
        nome: 'João Pedro Silva',
        curso: 'Ciência da Computação',
        foto: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=150&auto=format&fit=crop&q=80',
      },
    ],
  },
  {
    id: 'carona-3',
    motorista: {
      id: 'usr-nicolas',
      nome: 'Nicolas Isaac',
      curso: 'Ciência da Computação',
      foto: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=150&auto=format&fit=crop&q=80',
      nota: 4.8,
      alunoVerificado: true,
      celular: '(32) 99933-1200',
    },
    origem: 'Alto dos Passos',
    pontoEncontro: 'Posto Shell - Av. Rio Branco',
    destino: 'Campus Estrela Sul',
    pontoDesembarque: 'Estacionamento de Alunos',
    horarioSaida: '18:40',
    tolerancia: '10 min',
    turno: 'Noite',
    valorRateio: 'R$ 5,00',
    vagasTotais: 3,
    vagasDisponiveis: 3,
    carro: 'Volkswagen Polo Preto • QWR-1190',
    comodidades: ['Ar-condicionado', 'Playlist Pop Rock'],
    diasSemana: ['Seg', 'Qua', 'Qui'],
    passageiros: [],
  },
  {
    id: 'carona-4',
    motorista: {
      id: 'usr-mariana',
      nome: 'Mariana Duarte',
      curso: 'Psicologia',
      foto: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80',
      nota: 5.0,
      alunoVerificado: true,
      celular: '(32) 98844-5511',
    },
    origem: 'Granbery',
    pontoEncontro: 'Padaria do Granbery',
    destino: 'Campus Academia (Centro)',
    pontoDesembarque: 'Portaria Central',
    horarioSaida: '07:20',
    tolerancia: '5 min',
    turno: 'Manhã',
    valorRateio: 'R$ 4,50',
    vagasTotais: 3,
    vagasDisponiveis: 2,
    carro: 'Renault Kwid Laranja • ABC-4512',
    comodidades: ['Ar-condicionado'],
    diasSemana: ['Seg', 'Ter', 'Qua', 'Qui', 'Sex'],
    passageiros: [],
  },
  {
    id: 'carona-5',
    motorista: {
      id: 'usr-lucas',
      nome: 'Lucas Rezende',
      curso: 'Administração',
      foto: 'https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?w=150&auto=format&fit=crop&q=80',
      nota: 4.8,
      alunoVerificado: true,
      celular: '(32) 98401-2299',
    },
    origem: 'Benfica',
    pontoEncontro: 'Praça de Benfica (em frente ao banco)',
    destino: 'Campus Estrela Sul',
    pontoDesembarque: 'Portão 1 - Estrela Sul',
    horarioSaida: '18:10',
    tolerancia: '5 min',
    turno: 'Noite',
    valorRateio: 'R$ 7,50',
    vagasTotais: 4,
    vagasDisponiveis: 2,
    carro: 'Toyota Yaris Prata • JFE-9901',
    comodidades: ['Ar-condicionado', 'Conforto extra'],
    diasSemana: ['Ter', 'Qua', 'Qui'],
    passageiros: [],
  },
  {
    id: 'carona-6',
    motorista: {
      id: 'usr-beatriz',
      nome: 'Beatriz Vasconcelos',
      curso: 'Direito',
      foto: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
      nota: 4.9,
      alunoVerificado: true,
      celular: '(32) 99122-3344',
    },
    origem: 'Santa Luzia',
    pontoEncontro: 'Rua Ibitiguaia - Próximo ao supermercado',
    destino: 'Campus Academia (Centro)',
    pontoDesembarque: 'Portaria Central',
    horarioSaida: '07:30',
    tolerancia: '5 min',
    turno: 'Manhã',
    valorRateio: 'R$ 5,00',
    vagasTotais: 3,
    vagasDisponiveis: 1,
    carro: 'Nissan Kicks Cinza • KKS-3388',
    comodidades: ['Ar-condicionado', 'Música MPB'],
    diasSemana: ['Seg', 'Ter', 'Qua', 'Qui'],
    passageiros: [],
  },
];

export const mensagensIniciaisMock = [
  {
    id: 'msg-1',
    autor: 'Caio Castilho',
    texto: 'Boa noite pessoal! Saída pontual às 18:25 na praça do São Mateus.',
    horario: '18:10',
    propria: false,
    tipo: 'normal',
  },
  {
    id: 'msg-2',
    autor: 'Jonathan Delmonte',
    texto: 'Combinado! Já estou a caminho do ponto.',
    horario: '18:15',
    propria: false,
    tipo: 'normal',
  },
  {
    id: 'msg-3',
    autor: 'João Pedro Silva',
    texto: 'Cheguei no ponto de encontro!',
    horario: '18:20',
    propria: true,
    tipo: 'status',
  },
];
