const fotoPerfil = (genero, numero) =>
  `https://randomuser.me/api/portraits/${genero}/${numero}.jpg`;

const minutosAtras = (minutos) => new Date(Date.now() - minutos * 60 * 1000);

export const CAMPI = {
  academiaCentro: 'Campus Academia (Centro)',
  estrelaSul: 'Campus Estrela Sul',
};

export const TURNOS = {
  manha: 'Manhã',
  tarde: 'Tarde',
  noite: 'Noite',
};

export const DIAS_UTEIS = ['Seg', 'Ter', 'Qua', 'Qui', 'Sex'];

export const STATUS_VIAGEM = {
  confirmada: 'Confirmada',
  aguardandoSaida: 'Aguardando Saída',
  emAndamento: 'Em Andamento',
  concluida: 'Concluída',
};

export const TIPOS_MENSAGEM = {
  texto: 'texto',
  aviso: 'aviso',
};

export const CATEGORIAS_AVISO = {
  transito: 'transito',
  campus: 'campus',
  seguranca: 'seguranca',
  reserva: 'reserva',
  rota: 'rota',
  cancelamento: 'cancelamento',
};

export const AVISOS_RAPIDOS = [
  {
    id: 'cheguei-ponto',
    texto: 'Cheguei no ponto de encontro',
    icone: 'location-outline',
    resposta: 'Beleza, chego em 3 minutos.',
  },
  {
    id: 'atraso',
    texto: 'Atraso de 5 minutos, aguardem',
    icone: 'time-outline',
    resposta: 'Sem problema, te espero no ponto.',
  },
  {
    id: 'semaforo',
    texto: 'Carro parado no semáforo',
    icone: 'car-outline',
    resposta: 'Tranquilo, obrigado por avisar.',
  },
  {
    id: 'cheguei-portaria',
    texto: 'Já cheguei na portaria da faculdade',
    icone: 'school-outline',
    resposta: 'Boa aula! Na volta saio da portaria às 22:40.',
  },
];

const textoAvisoRapido = (avisoId) => AVISOS_RAPIDOS.find((aviso) => aviso.id === avisoId).texto;

export const estudantes = {
  joao: {
    id: 'joao',
    nome: 'João Pedro Silva',
    nomeCompleto: 'João Pedro Silva de Almeida',
    curso: 'Ciência da Computação',
    periodo: '7º período',
    matricula: '202301842',
    foto: fotoPerfil('men', 32),
    telefone: '(32) 9****-1842',
    nota: 4.9,
    totalAvaliacoes: 36,
    distribuicaoNotas: { 5: 34, 4: 1, 3: 1, 2: 0, 1: 0 },
    verificado: true,
    veiculo: { marca: 'Toyota', modelo: 'Yaris', cor: 'Branco', placa: 'RNA2E47' },
    chavePix: '5a2e9c7f-1d4b-4e68-a3f9-2c8d6b0e7a14',
    estatisticas: {
      viagensRealizadas: 42,
      caronasOferecidas: 18,
      economiaCombustivel: 340,
      horasEconomizadas: 14,
      pontualidade: 98,
      co2EvitadoKg: 212,
    },
    preferencias: {
      musica: 'Pop',
      climatizacao: 'Ar-condicionado ligado',
      conversa: 'Adora bater papo',
    },
  },
  caio: {
    id: 'caio',
    nome: 'Caio Castilho',
    nomeCompleto: 'Caio Castilho Soranço',
    curso: 'Ciência da Computação',
    periodo: '7º período',
    foto: fotoPerfil('men', 45),
    telefone: '(32) 9****-3307',
    nota: 4.8,
    totalAvaliacoes: 21,
    verificado: true,
  },
  gabriel: {
    id: 'gabriel',
    nome: 'Gabriel Caputo',
    nomeCompleto: 'Gabriel Caputo Morais',
    curso: 'Ciência da Computação',
    periodo: '7º período',
    foto: fotoPerfil('men', 51),
    telefone: '(32) 9****-6120',
    nota: 4.9,
    totalAvaliacoes: 17,
    verificado: true,
  },
  nicolas: {
    id: 'nicolas',
    nome: 'Nicolas Isaac',
    nomeCompleto: 'Nicolas Isaac Pinto de Jesus',
    curso: 'Ciência da Computação',
    periodo: '7º período',
    foto: fotoPerfil('men', 22),
    telefone: '(32) 9****-9054',
    nota: 5.0,
    totalAvaliacoes: 12,
    verificado: true,
  },
  jonathan: {
    id: 'jonathan',
    nome: 'Jonathan Delmonte',
    nomeCompleto: 'Jonathan Pereira Delmonte',
    curso: 'Ciência da Computação',
    periodo: '7º período',
    foto: fotoPerfil('men', 75),
    telefone: '(32) 9****-2718',
    nota: 4.9,
    totalAvaliacoes: 15,
    verificado: true,
  },
  lucas: {
    id: 'lucas',
    nome: 'Lucas Ferreira',
    nomeCompleto: 'Lucas Ferreira Rocha',
    curso: 'Engenharia de Software',
    periodo: '6º período',
    foto: fotoPerfil('men', 67),
    telefone: '(32) 9****-4471',
    nota: 4.9,
    totalAvaliacoes: 58,
    verificado: true,
  },
  mariana: {
    id: 'mariana',
    nome: 'Mariana Lopes',
    nomeCompleto: 'Mariana Lopes Carvalho',
    curso: 'Psicologia',
    periodo: '4º período',
    foto: fotoPerfil('women', 44),
    telefone: '(32) 9****-8836',
    nota: 5.0,
    totalAvaliacoes: 23,
    verificado: true,
  },
  rafael: {
    id: 'rafael',
    nome: 'Rafael Andrade',
    nomeCompleto: 'Rafael Andrade Couto',
    curso: 'Direito',
    periodo: '8º período',
    foto: fotoPerfil('men', 13),
    telefone: '(32) 9****-5290',
    nota: 4.8,
    totalAvaliacoes: 41,
    verificado: true,
  },
  beatriz: {
    id: 'beatriz',
    nome: 'Beatriz Campos',
    nomeCompleto: 'Beatriz Campos Ribeiro',
    curso: 'Arquitetura e Urbanismo',
    periodo: '5º período',
    foto: fotoPerfil('women', 65),
    telefone: '(32) 9****-1964',
    nota: 4.9,
    totalAvaliacoes: 33,
    verificado: true,
  },
  thiago: {
    id: 'thiago',
    nome: 'Thiago Nogueira',
    nomeCompleto: 'Thiago Nogueira Pires',
    curso: 'Administração',
    periodo: '3º período',
    foto: fotoPerfil('men', 3),
    telefone: '(32) 9****-7402',
    nota: 4.8,
    totalAvaliacoes: 9,
    verificado: true,
  },
  larissa: {
    id: 'larissa',
    nome: 'Larissa Vieira',
    nomeCompleto: 'Larissa Vieira Mendes',
    curso: 'Enfermagem',
    periodo: '6º período',
    foto: fotoPerfil('women', 68),
    telefone: '(32) 9****-6653',
    nota: 5.0,
    totalAvaliacoes: 27,
    verificado: true,
  },
  pedroHenrique: {
    id: 'pedro-henrique',
    nome: 'Pedro Henrique Duarte',
    nomeCompleto: 'Pedro Henrique Duarte Lima',
    curso: 'Engenharia Civil',
    periodo: '7º período',
    foto: fotoPerfil('men', 86),
    telefone: '(32) 9****-3185',
    nota: 4.8,
    totalAvaliacoes: 38,
    verificado: true,
  },
  camila: {
    id: 'camila',
    nome: 'Camila Rezende',
    nomeCompleto: 'Camila Rezende Alves',
    curso: 'Sistemas de Informação',
    periodo: '2º período',
    foto: fotoPerfil('women', 12),
    telefone: '(32) 9****-0917',
    nota: 4.9,
    totalAvaliacoes: 6,
    verificado: true,
  },
  felipe: {
    id: 'felipe',
    nome: 'Felipe Martins',
    nomeCompleto: 'Felipe Martins Barros',
    curso: 'Sistemas de Informação',
    periodo: '5º período',
    foto: fotoPerfil('men', 60),
    telefone: '(32) 9****-2546',
    nota: 4.9,
    totalAvaliacoes: 29,
    verificado: true,
  },
  anaClara: {
    id: 'ana-clara',
    nome: 'Ana Clara Moreira',
    nomeCompleto: 'Ana Clara Moreira Santos',
    curso: 'Fisioterapia',
    periodo: '3º período',
    foto: fotoPerfil('women', 90),
    telefone: '(32) 9****-8471',
    nota: 5.0,
    totalAvaliacoes: 11,
    verificado: true,
  },
  gustavo: {
    id: 'gustavo',
    nome: 'Gustavo Teixeira',
    nomeCompleto: 'Gustavo Teixeira Braga',
    curso: 'Engenharia de Produção',
    periodo: '6º período',
    foto: fotoPerfil('men', 41),
    telefone: '(32) 9****-5638',
    nota: 4.9,
    totalAvaliacoes: 44,
    verificado: true,
  },
};

export const usuarioLogadoInicial = estudantes.joao;

export const caronasIniciais = [
  {
    id: 'carona-sao-mateus-estrela-sul',
    motorista: estudantes.lucas,
    origem: {
      bairro: 'São Mateus',
      pontoEncontro: 'Praça do São Mateus, em frente à Igreja',
    },
    destino: { campus: CAMPI.estrelaSul, pontoChegada: 'Portaria Principal' },
    horarioSaida: '18:30',
    horarioRetorno: '22:40',
    toleranciaMinutos: 5,
    turno: TURNOS.noite,
    diasSemana: ['Ter', 'Qui'],
    veiculo: { marca: 'Chevrolet', modelo: 'Onix', cor: 'Prata', placa: 'RQK4B21' },
    comodidades: ['Ar-condicionado', 'Música', 'Porta-malas livre'],
    vagasTotais: 4,
    vagasDisponiveis: 1,
    passageiros: [estudantes.joao, estudantes.mariana, estudantes.jonathan],
    valorRateio: 6,
    distanciaKm: 7.8,
    chavePix: 'c2f7a9d4-3b1e-4f8a-9d62-7e5b1a0c4f93',
    observacoes: 'Sem fumo. Mochilas podem ir no porta-malas.',
    status: STATUS_VIAGEM.emAndamento,
  },
  {
    id: 'carona-cascatinha-academia',
    motorista: estudantes.beatriz,
    origem: {
      bairro: 'Cascatinha',
      pontoEncontro: 'Portão principal do Independência Shopping',
    },
    destino: { campus: CAMPI.academiaCentro, pontoChegada: 'Portaria Principal' },
    horarioSaida: '07:10',
    horarioRetorno: '12:20',
    toleranciaMinutos: 5,
    turno: TURNOS.manha,
    diasSemana: DIAS_UTEIS,
    veiculo: { marca: 'Fiat', modelo: 'Argo', cor: 'Vermelho', placa: 'SGT2C85' },
    comodidades: ['Ar-condicionado', 'Música'],
    vagasTotais: 4,
    vagasDisponiveis: 3,
    passageiros: [estudantes.thiago],
    valorRateio: 5,
    distanciaKm: 6.4,
    chavePix: '8e41b6c0-5d27-4a93-b1f8-2c9d6e7a3b15',
    observacoes: 'Saída pontual. Aceita mochila no colo.',
    status: STATUS_VIAGEM.confirmada,
  },
  {
    id: 'carona-alto-dos-passos-estrela-sul',
    motorista: estudantes.rafael,
    origem: {
      bairro: 'Alto dos Passos',
      pontoEncontro: 'Posto Shell da Av. Barão do Rio Branco',
    },
    destino: { campus: CAMPI.estrelaSul, pontoChegada: 'Portaria Principal' },
    horarioSaida: '18:40',
    horarioRetorno: '22:30',
    toleranciaMinutos: 5,
    turno: TURNOS.noite,
    diasSemana: ['Seg', 'Qua', 'Sex'],
    veiculo: { marca: 'Volkswagen', modelo: 'Polo', cor: 'Preto', placa: 'RTB7H10' },
    comodidades: ['Ar-condicionado', 'Porta-malas livre'],
    vagasTotais: 3,
    vagasDisponiveis: 1,
    passageiros: [estudantes.larissa, estudantes.camila],
    valorRateio: 4.5,
    distanciaKm: 5.9,
    chavePix: '4a9c2e71-0f3d-4b86-a5e2-9d1c7b8f6e04',
    observacoes: 'Sem fumo. Prefere conversa tranquila.',
    status: STATUS_VIAGEM.aguardandoSaida,
  },
  {
    id: 'carona-granbery-academia',
    motorista: estudantes.gabriel,
    origem: {
      bairro: 'Granbery',
      pontoEncontro: 'Portão do Colégio Granbery, Rua Batista de Oliveira',
    },
    destino: { campus: CAMPI.academiaCentro, pontoChegada: 'Portaria Principal' },
    horarioSaida: '07:20',
    horarioRetorno: '12:10',
    toleranciaMinutos: 3,
    turno: TURNOS.manha,
    diasSemana: DIAS_UTEIS,
    veiculo: { marca: 'Renault', modelo: 'Sandero', cor: 'Cinza', placa: 'QNX3A62' },
    comodidades: ['Música', 'Porta-malas livre'],
    vagasTotais: 4,
    vagasDisponiveis: 4,
    passageiros: [],
    valorRateio: 3,
    distanciaKm: 1.8,
    chavePix: '6d3f8b25-9a4c-4e17-8b0d-3f2a5c9e1d78',
    observacoes: 'Trajeto curto pelo Centro. Aceita mochila no colo.',
    status: STATUS_VIAGEM.confirmada,
  },
  {
    id: 'carona-santa-luzia-estrela-sul',
    motorista: estudantes.pedroHenrique,
    origem: {
      bairro: 'Santa Luzia',
      pontoEncontro: 'Praça da Igreja de Santa Luzia',
    },
    destino: { campus: CAMPI.estrelaSul, pontoChegada: 'Portaria Principal' },
    horarioSaida: '18:20',
    horarioRetorno: '22:30',
    toleranciaMinutos: 5,
    turno: TURNOS.noite,
    diasSemana: ['Seg', 'Ter', 'Qua', 'Qui'],
    veiculo: { marca: 'Fiat', modelo: 'Mobi', cor: 'Branco', placa: 'RFZ9D34' },
    comodidades: ['Ar-condicionado'],
    vagasTotais: 3,
    vagasDisponiveis: 1,
    passageiros: [estudantes.nicolas, estudantes.anaClara],
    valorRateio: 4,
    distanciaKm: 4.2,
    chavePix: 'f1b8d3a6-7c2e-4d59-a0b4-8e6f2c1d9a37',
    observacoes: 'Carro compacto, mochilas no colo.',
    status: STATUS_VIAGEM.aguardandoSaida,
  },
  {
    id: 'carona-benfica-academia',
    motorista: estudantes.felipe,
    origem: {
      bairro: 'Benfica',
      pontoEncontro: 'Praça de Benfica, ao lado da Igreja Matriz',
    },
    destino: { campus: CAMPI.academiaCentro, pontoChegada: 'Portaria Principal' },
    horarioSaida: '18:00',
    horarioRetorno: '22:40',
    toleranciaMinutos: 5,
    turno: TURNOS.noite,
    diasSemana: DIAS_UTEIS,
    veiculo: { marca: 'Honda', modelo: 'Fit', cor: 'Cinza', placa: 'PWE5J28' },
    comodidades: ['Ar-condicionado', 'Música', 'Porta-malas livre'],
    vagasTotais: 4,
    vagasDisponiveis: 3,
    passageiros: [estudantes.thiago],
    valorRateio: 9,
    distanciaKm: 14.5,
    chavePix: '2e6a9f14-8b3d-4c70-9e5a-1d7b4c8f0e62',
    observacoes: 'Aceita embarque no caminho pela Av. Juscelino Kubitschek.',
    status: STATUS_VIAGEM.confirmada,
  },
  {
    id: 'carona-centro-estrela-sul',
    motorista: estudantes.caio,
    origem: {
      bairro: 'Centro',
      pontoEncontro: 'Parque Halfeld, lado da Av. Rio Branco',
    },
    destino: { campus: CAMPI.estrelaSul, pontoChegada: 'Portaria Principal' },
    horarioSaida: '07:00',
    horarioRetorno: '12:15',
    toleranciaMinutos: 5,
    turno: TURNOS.manha,
    diasSemana: DIAS_UTEIS,
    veiculo: { marca: 'Hyundai', modelo: 'HB20', cor: 'Azul', placa: 'QWE1F47' },
    comodidades: ['Ar-condicionado', 'Música'],
    vagasTotais: 4,
    vagasDisponiveis: 2,
    passageiros: [estudantes.joao, estudantes.jonathan],
    valorRateio: 4.5,
    distanciaKm: 6,
    chavePix: '9b4e1c87-2f6a-4d3b-8c95-5a0e7d2f1b46',
    observacoes: 'Sem fumo.',
    status: STATUS_VIAGEM.confirmada,
  },
  {
    id: 'carona-manoel-honorio-academia',
    motorista: estudantes.mariana,
    origem: {
      bairro: 'Manoel Honório',
      pontoEncontro: 'Praça do Manoel Honório, ponto de ônibus',
    },
    destino: { campus: CAMPI.academiaCentro, pontoChegada: 'Portaria Principal' },
    horarioSaida: '07:15',
    horarioRetorno: '12:20',
    toleranciaMinutos: 5,
    turno: TURNOS.manha,
    diasSemana: ['Ter', 'Qui'],
    veiculo: { marca: 'Renault', modelo: 'Kwid', cor: 'Laranja', placa: 'SHA4E19' },
    comodidades: ['Música'],
    vagasTotais: 3,
    vagasDisponiveis: 1,
    passageiros: [estudantes.pedroHenrique, estudantes.larissa],
    valorRateio: 3.5,
    distanciaKm: 3.2,
    chavePix: '7c1d5e92-4a8b-4f36-b2e1-6d9c3a7f8e05',
    observacoes: 'Aceita mochila no colo.',
    status: STATUS_VIAGEM.confirmada,
  },
  {
    id: 'carona-sao-mateus-academia',
    motorista: estudantes.gustavo,
    origem: {
      bairro: 'São Mateus',
      pontoEncontro: 'Rua São Mateus, em frente à padaria da esquina',
    },
    destino: { campus: CAMPI.academiaCentro, pontoChegada: 'Portaria Principal' },
    horarioSaida: '07:05',
    horarioRetorno: '12:10',
    toleranciaMinutos: 5,
    turno: TURNOS.manha,
    diasSemana: DIAS_UTEIS,
    veiculo: { marca: 'Nissan', modelo: 'Versa', cor: 'Prata', placa: 'RMC8G53' },
    comodidades: ['Ar-condicionado', 'Porta-malas livre'],
    vagasTotais: 3,
    vagasDisponiveis: 0,
    passageiros: [estudantes.rafael, estudantes.camila, estudantes.anaClara],
    valorRateio: 4,
    distanciaKm: 4.6,
    chavePix: '3f8c6a1d-5e2b-4a97-9d40-b7e1c5f2a863',
    observacoes: 'Sem fumo.',
    status: STATUS_VIAGEM.confirmada,
  },
  {
    id: 'carona-cascatinha-estrela-sul-joao',
    motorista: estudantes.joao,
    origem: {
      bairro: 'Cascatinha',
      pontoEncontro: 'Ponto de ônibus da Av. Presidente Itamar Franco',
    },
    destino: { campus: CAMPI.estrelaSul, pontoChegada: 'Portaria Principal' },
    horarioSaida: '18:15',
    horarioRetorno: '22:30',
    toleranciaMinutos: 5,
    turno: TURNOS.noite,
    diasSemana: ['Seg', 'Qua', 'Sex'],
    veiculo: estudantes.joao.veiculo,
    comodidades: ['Ar-condicionado', 'Música'],
    vagasTotais: 3,
    vagasDisponiveis: 2,
    passageiros: [estudantes.gabriel],
    valorRateio: 5,
    distanciaKm: 6.1,
    chavePix: estudantes.joao.chavePix,
    observacoes: 'Sem fumo. Aceita mochila no colo.',
    status: STATUS_VIAGEM.aguardandoSaida,
  },
  {
    id: 'carona-alto-dos-passos-academia-concluida',
    motorista: estudantes.rafael,
    origem: {
      bairro: 'Alto dos Passos',
      pontoEncontro: 'Posto Shell da Av. Barão do Rio Branco',
    },
    destino: { campus: CAMPI.academiaCentro, pontoChegada: 'Portaria Principal' },
    horarioSaida: '07:10',
    horarioRetorno: '12:20',
    toleranciaMinutos: 5,
    turno: TURNOS.manha,
    diasSemana: ['Seg'],
    veiculo: { marca: 'Volkswagen', modelo: 'Polo', cor: 'Preto', placa: 'RTB7H10' },
    comodidades: ['Ar-condicionado', 'Porta-malas livre'],
    vagasTotais: 3,
    vagasDisponiveis: 1,
    passageiros: [estudantes.joao, estudantes.camila],
    valorRateio: 3.5,
    distanciaKm: 3.4,
    chavePix: '4a9c2e71-0f3d-4b86-a5e2-9d1c7b8f6e04',
    observacoes: 'Sem fumo.',
    status: STATUS_VIAGEM.concluida,
  },
  {
    id: 'carona-cascatinha-estrela-sul-concluida',
    motorista: estudantes.joao,
    origem: {
      bairro: 'Cascatinha',
      pontoEncontro: 'Ponto de ônibus da Av. Presidente Itamar Franco',
    },
    destino: { campus: CAMPI.estrelaSul, pontoChegada: 'Portaria Principal' },
    horarioSaida: '18:15',
    horarioRetorno: '22:30',
    toleranciaMinutos: 5,
    turno: TURNOS.noite,
    diasSemana: ['Qua'],
    veiculo: estudantes.joao.veiculo,
    comodidades: ['Ar-condicionado', 'Música'],
    vagasTotais: 3,
    vagasDisponiveis: 0,
    passageiros: [estudantes.mariana, estudantes.jonathan, estudantes.caio],
    valorRateio: 5,
    distanciaKm: 6.1,
    chavePix: estudantes.joao.chavePix,
    observacoes: 'Sem fumo. Aceita mochila no colo.',
    status: STATUS_VIAGEM.concluida,
  },
];

export const mensagensChatIniciais = [
  {
    id: 'mensagem-1',
    autor: estudantes.lucas,
    texto: 'Boa noite, pessoal! Hoje saio às 18:30 da Praça do São Mateus, em frente à igreja.',
    tipo: TIPOS_MENSAGEM.texto,
    enviadaEm: minutosAtras(34),
    lida: true,
  },
  {
    id: 'mensagem-2',
    autor: estudantes.mariana,
    texto: 'Combinado! Chego uns minutos antes.',
    tipo: TIPOS_MENSAGEM.texto,
    enviadaEm: minutosAtras(31),
    lida: true,
  },
  {
    id: 'mensagem-3',
    autor: estudantes.jonathan,
    texto: 'Vou levar o notebook na mochila. Pode ir no porta-malas?',
    tipo: TIPOS_MENSAGEM.texto,
    enviadaEm: minutosAtras(27),
    lida: true,
  },
  {
    id: 'mensagem-4',
    autor: estudantes.lucas,
    texto: 'Pode sim, o porta-malas está livre.',
    tipo: TIPOS_MENSAGEM.texto,
    enviadaEm: minutosAtras(25),
    lida: true,
  },
  {
    id: 'mensagem-5',
    autor: estudantes.lucas,
    texto: textoAvisoRapido('atraso'),
    tipo: TIPOS_MENSAGEM.aviso,
    enviadaEm: minutosAtras(14),
    lida: true,
  },
  {
    id: 'mensagem-6',
    autor: estudantes.mariana,
    texto: textoAvisoRapido('cheguei-ponto'),
    tipo: TIPOS_MENSAGEM.aviso,
    enviadaEm: minutosAtras(11),
    lida: false,
  },
  {
    id: 'mensagem-7',
    autor: estudantes.joao,
    texto: textoAvisoRapido('cheguei-ponto'),
    tipo: TIPOS_MENSAGEM.aviso,
    enviadaEm: minutosAtras(9),
    lida: true,
  },
  {
    id: 'mensagem-8',
    autor: estudantes.lucas,
    texto: textoAvisoRapido('semaforo'),
    tipo: TIPOS_MENSAGEM.aviso,
    enviadaEm: minutosAtras(3),
    lida: false,
  },
];

export const avisosIniciais = [
  {
    id: 'aviso-transito-itamar-franco',
    categoria: CATEGORIAS_AVISO.transito,
    titulo: 'Trânsito intenso na Av. Presidente Itamar Franco',
    descricao: 'Lentidão no sentido Centro entre 18h e 19h. Combine a saída com 10 minutos de antecedência.',
    criadoEm: minutosAtras(12),
    lido: false,
  },
  {
    id: 'aviso-portaria-estrela-sul',
    categoria: CATEGORIAS_AVISO.campus,
    titulo: 'Entrada do Estrela Sul liberada',
    descricao: 'A portaria principal voltou a funcionar normalmente depois da manutenção.',
    criadoEm: minutosAtras(47),
    lido: false,
  },
  {
    id: 'aviso-ponto-iluminado-centro',
    categoria: CATEGORIAS_AVISO.seguranca,
    titulo: 'Ponto de encontro iluminado no Centro',
    descricao: 'Para embarques à noite, prefira o Parque Halfeld, lado da Av. Rio Branco, que tem iluminação e câmeras.',
    criadoEm: minutosAtras(3 * 60),
    lido: true,
  },
  {
    id: 'aviso-semana-academica',
    categoria: CATEGORIAS_AVISO.campus,
    titulo: 'Semana acadêmica no Campus Academia',
    descricao: 'Na quinta-feira, embarque e desembarque apenas pela portaria principal.',
    criadoEm: minutosAtras(26 * 60),
    lido: true,
  },
];

export const avaliacoesRecebidas = [
  {
    id: 'avaliacao-1',
    autor: estudantes.mariana,
    nota: 5,
    dataCarona: '23/09/2026',
    comentario: 'Pontual e dirige com calma. A conversa no caminho deixa a viagem mais leve.',
  },
  {
    id: 'avaliacao-2',
    autor: estudantes.jonathan,
    nota: 5,
    dataCarona: '23/09/2026',
    comentario: 'Chegou no horário combinado e avisou pelo app quando estava perto do ponto.',
  },
  {
    id: 'avaliacao-3',
    autor: estudantes.caio,
    nota: 5,
    dataCarona: '18/09/2026',
    comentario: 'Carro limpo, ar-condicionado ligado e deixou todo mundo na portaria.',
  },
  {
    id: 'avaliacao-4',
    autor: estudantes.camila,
    nota: 4,
    dataCarona: '15/09/2026',
    comentario: 'Viagem tranquila. Atrasou alguns minutos por causa do trânsito na Itamar Franco.',
  },
];
